name: Discord Push Notification

on:
  push:

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send Discord Notification
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          REPO_NAME=${{ github.repository }}
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          USER_NAME=${{ github.actor }}
          USER_LINK="https://github.com/${USER_NAME}"
          REPO_LINK="https://github.com/${REPO_NAME}"
          BRANCH_LINK="${REPO_LINK}/tree/${BRANCH_NAME}"
          
          COMMIT_LIST=$(git log -n 10 --pretty=format:"| [%h](${REPO_LINK}/commit/%H) : %s - %an" --abbrev=7)

          MESSAGE="**${USER_NAME}** (${USER_LINK}) pushed to branch **${BRANCH_NAME}** (${BRANCH_LINK}) of **${REPO_NAME}** (${REPO_LINK})\n\n${COMMIT_LIST}"

          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{\"content\": \"${MESSAGE}\"}" \
               $DISCORD_WEBHOOK_URL
